blank_issues_enabled: false
contact_links:
  - name: BrowserBox Community Support
    url: https://github.com/BrowserBox/BrowserBox/discussions
    about: Please ask and answer questions here.
  - name: BrowserBox security.txt
    url: https://dosyago.com/security.txt
    about: Please report security vulnerabilities here.
  - name: Paid licensee support
    url: mailto:support@dosyago.com
    about: If you already have a license email questions here for priority support.
  - name: License inquiries and purchases
    url: mailto:sales@dosyago.com
    about: Reach out to our friendly sales team!
